name: Swift Linting

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Swift
              uses: actions/setup-swift@v3
              with:
                  swift-version: '6.2'

            - name: Verify Swift version
              run: swift --version

            - name: Run SwiftLint
              run: swiftlint lint --strict